repos:
- repo: https://github.com/commitizen-tools/commitizen
  rev: v2.20.4
  hooks:
    - id: commitizen
      stages: [commit-msg]

-   repo: https://github.com/mwouts/jupytext
    rev: v1.13.6  # CURRENT_TAG/COMMIT_HASH
    hooks:
    - id: jupytext
      args: [--sync, --to py:light --pipe, black]
      additional_dependencies:
        - black==21.6b0 # Matches hook

- repo: https://github.com/timothycrosley/isort
  rev: 5.10.1
  hooks:
  - id: isort
    args: 
    - '-m'
    - '3'
    - '--tc'
    - '--line-length'
    - '78'
    - --use-parentheses

- repo: https://github.com/ambv/black
  rev: 22.1.0
  hooks:
  - id: black
    language_version: python3.9
    args:
    - --line-length
    - "80"
    - --exclude
    - '/(\.git|\.hg|\.mypy_cache|\.tox|\.devspace|\.venv|\.vscode|build|dist|.*/jupyter)/'

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  - id: flake8

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v0.931'
  hooks:
  - id: mypy
    additional_dependencies:
      - "types-PyYAML"
      - "numpy"
    exclude:
      features/.*\.py
    args:
    - --show-traceback
    - --ignore-missing-imports
